sonar.projectKey=outoft3n_jiancha-travel
sonar.organization=outoft3n

sonar.sources=implementations/backend/src
sonar.tests=implementations/backend/tests

sonar.javascript.lcov.reportPaths=implementations/backend/coverage/lcov.info

sonar.sourceEncoding=UTF-8